version: '3.8'
services:
  frontend:
    image: myapp-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: myapp-backend
    build: ./backend
    ports:
      - "5000:5000"
